spring:
  application:
    name: movieflix
  datasource:
    url: jdbc:postgresql://${HOST}:${DBPORT}/${DBNAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
movieflix:
  security:
    secret: ${SECRET:MAKDNLN1833N1JN31LBN31I73B13K1B3871B}
