spring:
  application:
    name: movieflix
  datasource:
    url: jdbc:postgresql:${HOST}:${DBPORT}/${DBNAME}
    ursername: ${USER}
    password: ${PASS}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

    flyway:
      enable: true
